### ISSUE TITLE
life sign

### ISSUE THREAD

**Issue by BieberleA** [HZDR-FWDF/ddafa#35]
Hallo Jan. Erreiche ich dich noch über dieses Board? Ich möchte in naher Zukunft mit dem Paris und Glados Programm wieder arbeiten und checken ob du mir über diesen Kanal mit helfen kannst. Viele Grüße... André.

**Comment by j-stephan** [comment]
Hallo André, ja, ich lese hier noch mit und stehe natürlich für Fragen zur Verfügung.

**Comment by BieberleA** [comment]
Super! Ich melde mich wenn ich nicht weiter komme. Werde ab Mitte nächster Woche mit PARIS starten. Beste Grüße.

**Comment by BieberleA** [comment]
Sooo ... es hat zwar 1.5 a gedauert, aber ich melde mich doch tatsächlich wieder über diesen Kanal. Hättest du eventuell mal 15 min per Zoom für mich? Ich würde mich gern mit dir über den aktuellen Zustand von PARIS abstimmen und gerne wissen wollen, wie deine Pläne mit diesem Tool sind. Hättest du diese Woche mal Zeit dafür? Ich denke, dass mehr Small-Talk als Businesses gesprochen wird :-) ... Bis später ... André

**Comment by j-stephan** [comment]
Siehe dienstliche E-Mail ;-)
